version: '3'

services:
  app:
    build: ./.docker/
    container_name: omotenashi
    # links:
    #   - mysql
    ports:
      - 9000:80
    volumes:
      - ./:/var/www
    tty: true
    privileged: true
    command: /sbin/init

networks:
  default:
    external:
      name: agito
