version: '3'

services:
  app:
    build: ./.docker/
    container_name: omotenashi
    ports:
      - 9000:80
    volumes:
      - ./:/var/www
    environment:
      - VIRTUAL_HOST=docker.omotenashi.today
    command: /sbin/init
    privileged: true
    tty: true

networks:
  default:
    external:
      name: agito
